import {
  EmitContext, emitFile, listServices, getNamespaceFullName,
  navigateTypesInNamespace, Model, Namespace, Interface, Program, Type, Scalar,
} from "@typespec/compiler";

export type EmitterOptions = { "emitter-output-dir": string };
interface FieldInfo { name: string; type: Type; optional: boolean; }
interface ServiceInfo { namespace: Namespace; iface: Interface; serviceName: string; models: Model[]; }

function extractFields(model: Model): FieldInfo[] {
  const fields: FieldInfo[] = [];
  for (const [name, prop] of model.properties) fields.push({ name, type: prop.type, optional: prop.optional ?? false });
  return fields;
}

function isStringType(t: Type): boolean { return (t.kind === "Scalar" && (t as Scalar).name === "string"); }
function isIntType(t: Type): boolean { return t.kind === "Scalar" && ["int8","int16","int32","int64","uint8","uint16","uint32","uint64","integer"].includes((t as Scalar).name); }
function isFloatType(t: Type): boolean { return t.kind === "Scalar" && ["float","float32","float64"].includes((t as Scalar).name); }
function isBoolType(t: Type): boolean { return t.kind === "Scalar" && (t as Scalar).name === "boolean"; }
function isArrayType(t: Type): boolean { return t.kind === "Model" && !!(t as Model).indexer; }
function arrayElemType(t: Type): Type { return (t.kind === "Model" && (t as Model).indexer) ? (t as Model).indexer!.value : t; }

function typeToPython(t: Type): string {
  if (isStringType(t)) return "str";
  if (isIntType(t)) return "int";
  if (isFloatType(t)) return "float";
  if (isBoolType(t)) return "bool";
  if (isArrayType(t)) return `list[${typeToPython(arrayElemType(t))}]`;
  if (t.kind === "Model") return t.name || "Any";
  return "Any";
}

function collectServices(program: Program): ServiceInfo[] {
  const services = listServices(program);
  const result: ServiceInfo[] = [];
  function collectFromNs(ns: Namespace) {
    for (const [,iface] of ns.interfaces) {
      const models: Model[] = []; const seen = new Set<string>();
      navigateTypesInNamespace(ns, { model: (m: Model) => { if (m.name && !seen.has(m.name)) { models.push(m); seen.add(m.name); } } });
      result.push({ namespace: ns, iface, serviceName: iface.name, models });
    }
  }
  for (const svc of services) collectFromNs(svc.type);
  if (result.length === 0) { const g = program.getGlobalNamespaceType(); for (const [, ns] of g.namespaces) collectFromNs(ns); collectFromNs(g); }
  return result;
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const program = context.program;
  const outputDir = context.emitterOutputDir;
  for (const svc of collectServices(program)) {
    const lines: string[] = [];
    lines.push("# Generated by @specodec/typespec-specodec-python. DO NOT EDIT.");
    lines.push("from __future__ import annotations");
    lines.push("from dataclasses import dataclass, field");
    lines.push("from typing import Optional");
    lines.push("import specodec");
    lines.push("");
    for (const m of svc.models) {
      if (!m.name) continue;
      lines.push("@dataclass");
      lines.push(`class ${m.name}:`);
      const fields = extractFields(m);
      if (fields.length === 0) lines.push("    pass");
      for (const f of fields) {
        const t = typeToPython(f.type);
        if (f.optional) lines.push(`    ${f.name}: Optional[${t}] = None`);
        else lines.push(`    ${f.name}: ${t}`);
      }
      lines.push("");
    }
    const snake = svc.serviceName.replace(/([A-Z])/g, (m: string, c: string, i: number) => (i ? "_" : "") + c.toLowerCase());
    await emitFile(program, { path: `${outputDir}/${snake}_types.py`, content: lines.join("\n") });
  }
}
